name: Linux Packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build and packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson ninja-build \
            fonts-noto \
            build-essential \
            curl gettext libxml2-utils \
            python3 \
            pkg-config \
            cmake \
            libglib2.0-dev libgtk-4-dev libgtkmm-4.0-dev \
            wget unzip \
            libfuse2t64 \
            libgtk-4-1 libgtkmm-4.0-0 \
            xdg-desktop-portal xdg-desktop-portal-gtk xdg-utils \
          
          # AppImage tooling
          sudo apt-get install -y \
            libglib2.0-bin \
            libgtk-4-bin 

          # Flatpak stuff
          # ...

      - name: Configure and build
        run: |
          meson setup build --prefix=/usr
          ninja -C build

      - name: Create source tarball
        run: |
          mkdir -p artifacts
          tar czf artifacts/packitup-${{ github.ref_name }}.tar.gz \
            -C build .

      - name: Prepare AppDir
        run: |
          rm -rf AppDir
          mkdir -p AppDir/usr/bin AppDir/usr/share/{applications,icons/hicolor,locale/pt_BR/LC_MESSAGES,locale/en_US/LC_MESSAGES} AppDir/usr/share/licenses AppDir/usr/share/glib-2.0/schemas
          mkdir -p AppDir/usr/share/icons/hicolor/{16x16,22x22,24x24,32x32,48x48,64x64,128x128,256x256,512x512}/apps
          mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
          cp build/src/packitup AppDir/usr/bin
          cp build/src/packitup.desktop AppDir/usr/share/applications
          cp LICENSE AppDir/usr/share/licenses
          cp build/po/pt_BR/LC_MESSAGES/packitup.mo AppDir/usr/share/locale/pt_BR/LC_MESSAGES
          cp build/po/en_US/LC_MESSAGES/packitup.mo AppDir/usr/share/locale/en_US/LC_MESSAGES
          cp src/tech.bm7.packitup.gschema.xml AppDir/usr/share/glib-2.0/schemas
          cp src/icons/hicolor/16x16/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/16x16/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/22x22/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/22x22/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/24x24/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/24x24/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/32x32/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/32x32/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/48x48/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/48x48/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/64x64/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/64x64/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/128x128/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/128x128/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/256x256/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/256x256/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/512x512/apps/tech.bm7.packitup.png AppDir/usr/share/icons/hicolor/512x512/apps/tech.bm7.packitup.png
          cp src/icons/hicolor/scalable/apps/tech.bm7.packitup.svg AppDir/usr/share/icons/hicolor/scalable/apps/tech.bm7.packitup.svg
          glib-compile-schemas AppDir/usr/share/glib-2.0/schemas

      - name: Download AppImageTool
        run: |
          wget -qO appimagetool.AppImage \
            https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool.AppImage

      - name: Build AppImage
        run: |
          mv AppDir PackItUP.AppDir
          ./appimagetool.AppImage PackItUP.AppDir \
            artifacts/PackItUP-${{ github.ref_name }}.AppImage

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            artifacts/packitup-${{ github.ref_name }}.tar.gz
            artifacts/PackItUP-${{ github.ref_name }}.AppImage
