name: Linux Packaging

on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create source tarball
        id: make_tar
        run: |
          tar czf packitup-${{ github.ref_name }}.tar.gz \
            --exclude .git \
            --transform "s,^,packitup-${{ github.ref_name }}/," \
            .

      - name: Upload as Release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./packitup-${{ github.ref_name }}.tar.gz
          asset_name: packitup-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
