name: Linux Packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create source tarball
        run: |
          mkdir -p artifacts
          tar czf artifacts/packitup-${{ github.ref_name }}.tar.gz . .
           - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            artifacts/packitup-${{ github.ref_name }}.tar.gz
