name: Linux Packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build and packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson ninja-build \
            fonts-noto \
            build-essential \
            curl gettext libxml2-utils \
            python3 \
            pkg-config \
            cmake \
            libglib2.0-dev libgtk-4-dev libgtkmm-4.0-dev \
            wget unzip \
            libfuse2t64 \
            patchelf \
            libgtk-4-1 libgtkmm-4.0-0 \
            xdg-desktop-portal xdg-desktop-portal-gtk xdg-utils \
          
          # AppImage tooling
          sudo apt-get install -y \
            libglib2.0-bin \
            libgtk-4-bin 

          # Flatpak stuff
          # ...

      - name: Configure and build
        run: |
          meson setup build --prefix=/usr
          meson compile -C build

      - name: Install Source files into DESTDIR
        run: |
          rm -rf AppDir
          mkdir AppDir
          meson install -C build --destdir "$PWD/AppDir"
          glib-compile-schemas   AppDir/usr/share/glib-2.0/schemas
          gtk-update-icon-cache -f -t AppDir/usr/share/icons/hicolor 
          
      - name: Create source tarball
        run: |
          mkdir -p artifacts
          tar czf artifacts/packitup-${{ github.ref_name }}.tar.gz \
            -C AppDir .

      - name: Prepare AppDir
        run: |
          cp src/icons/hicolor/512x512/apps/tech.bm7.packitup.png AppDir/
          cp src/icons/hicolor/scalable/apps/tech.bm7.packitup.svg AppDir/tech.bm7.packitup.svg
          cp build/src/packitup.desktop AppDir/

      - name: Create AppRun
        run: |
          cat > AppDir/AppRun << 'EOF'
          #!/bin/env bash
          set -eo pipefail
          
          if [ -z "$APPDIR" ]; then
            SOURCE="${BASH_SOURCE[0]}"
            while [ -h "$SOURCE" ]; do
              DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
              SOURCE="$(readlink "$SOURCE")"
              [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
            done
            DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
            APPDIR="$DIR"
          fi

          export XDG_DATA_DIRS="$APPDIR/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
          export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"

          export LD_LIBRARY_PATH="$APPDIR/usr/lib${LD_LIBRARY_PATH:+":$LD_LIBRARY_PATH"}"
          export TEXTDOMAINDIR="$APPDIR/usr/share/locale"

          exec "$APPDIR/usr/bin/packitup"
          EOF
          chmod +x PackItUP.AppDir/AppRun

      - name: Run linuxdeploy to bundle shared libraries (.so files)
        run: |
          # ensure our target exists
          wget -O linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --executable AppDir/usr/bin/packitup \
            --output none \
            --no-desktop-file \
            --no-icons \
            --no-copyright \
            --no-strip

      #- name: Fix binary RPATH
      #  run: |
          # so the loader looks in ../lib (i.e. AppDir/usr/lib) first
          # Using linuxdeploy, not needed now
          #patchelf --set-rpath '$ORIGIN/../lib' AppDir/usr/bin/packitup

      - name: Download AppImageTool
        run: |
          wget -qO appimagetool.AppImage \
            https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool.AppImage

      - name: Build AppImage
        run: |
          mv AppDir PackItUP.AppDir
          ./appimagetool.AppImage PackItUP.AppDir \
            artifacts/PackItUP-${{ github.ref_name }}.AppImage

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: |
            artifacts/packitup-${{ github.ref_name }}.tar.gz
            artifacts/PackItUP-${{ github.ref_name }}.AppImage
