
name: Windows Packaging

on:
  release:
    types: [published]    # fires only when you publish a Release in GitHub
  workflow_dispatch:      # optional: allows manual reruns from the Actions UI

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-gtkmm4
            nsis
            meson
            ninja

      - name: Configure & build
        run: |
          meson setup build-win --cross-file=ci/windows-cross.txt
          ninja -C build-win

      - name: Collect DLLs & build installer
        run: |
          mkdir dist
          cp build-win/packitup.exe dist/
          cp /ucrt64/bin/*.dll dist/
          makensis installer.nsi

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: |
            dist/**
            PackItUP-*.exe


  # ───────────────────────────────────────────────────────────────────────────────
  msys2-package:
    name: Build MSYS2 PKGBUILD
    runs-on: ubuntu-latest
    container:
      image: msys2/msys2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap MSYS2 & install toolchain
        run: |
          pacman -Syuu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-meson

      - name: Build PKGBUILD
        working-directory: packaging/msys2
        run: |
          # skip PGP for CI
          makepkg --skippgpcheck --noconfirm

      - name: Upload MSYS2 package
        uses: actions/upload-artifact@v3
        with:
          name: msys2-pkg
          path: packaging/msys2/*.pkg.tar.zst
