name: Windows Packaging

on:
  release:
    types: [published]    # fires only when you publish a Release in GitHub
  workflow_dispatch:      # optional: allows manual reruns from the Actions UI

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2 UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-binutils
            mingw-w64-ucrt-x86_64-gtk4
            mingw-w64-ucrt-x86_64-gtkmm4
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-glib2
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-gettext-tools
            mingw-w64-ucrt-x86_64-libxml2
            mingw-w64-ucrt-x86_64-nsis
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja

      - name: Fix archiver name
        run: |
          ln -s "$(which ar)" /ucrt64/bin/x86_64-w64-mingw32-ar.exe

      - name: Configure & build
        run: |
          meson setup build-win --cross-file=ci/windows-cross.txt
          ninja -C build-win

      - name: Collect DLLs
        run: |
          rm -rf dist
          mkdir -p dist
          cp build-win/src/packitup.exe dist/
          cp /ucrt64/bin/*.dll dist/

      - name: Compile GSettings schemas
        run: |
          mkdir -p dist/share/glib-2.0/schemas
          cp src/*.gschema.xml dist/share/glib-2.0/schemas
          glib-compile-schemas dist/share/glib-2.0/schemas

      - name: Copy gettext tranlations
        run: |
          mkdir -p dist/share/locale/pt_BR/LC_MESSAGES
          mkdir -p dist/share/locale/en_US/LC_MESSAGES
          cp build-win/po/pt_BR/LC_MESSAGES/packitup.mo \
            dist/share/locale/pt_BR/LC_MESSAGES/packitup.mo
          cp build-win/po/en_US/LC_MESSAGES/packitup.mo \
            dist/share/locale/en_US/LC_MESSAGES/packitup.mo

      - name: Build Installer
        run: |
          makensis installer.nsi


      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: |
            dist/**
            PackItUP-*.exe
